# Generated by Django 3.2.22 on 2023-12-16 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('7:30', '7:30'), ('7:50', '7:50'), ('8:10', '8:10'), ('8:30', '8:30'), ('8:50', '8:50'), ('9:10', '9:10'), ('9:30', '9:30'), ('9:50', '9:50'), ('10:10', '10:10'), ('10:30', '10:30'), ('10:50', '10:50'), ('11:10', '11:10'), ('11:30', '11:30'), ('11:50', '11:50'), ('12:10', '12:10'), ('12:30', '12:30'), ('12:50', '12:50'), ('13:10', '13:10'), ('13:30', '13:30'), ('13:50', '13:50'), ('14:10', '14:10'), ('14:30', '14:30'), ('14:50', '14:50'), ('15:10', '15:10'), ('15:30', '15:30'), ('15:50', '15:50'), ('16:10', '16:10'), ('16:30', '16:30'), ('16:50', '16:50'), ('17:10', '17:10'), ('17:30', '17:30'), ('17:50', '17:50')], default='7:30', max_length=10)),
                ('number_of_players', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('member', models.BooleanField(default=False)),
                ('buggy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
