# Generated by Django 3.2.22 on 2023-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_players',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
